application: guestbook
version: 1
runtime: php55
api_version: 1

handlers:
- url: .*
  script: main.php

env_variables:
 DEVELOPMENT_DB_HOST: ''
 DEVELOPMENT_DB_USERNAME: 'root'
 DEVELOPMENT_DB_PASSWORD: ''
 DEVELOPMENT_DB_NAME: 'guestbook'
 PRODUCTION_CLOUD_SQL_INSTANCE: '/cloudsql/guestbook:my-cloudsql-instance'
 PRODUCTION_DB_USERNAME: ''
 PRODUCTION_DB_PASSWORD: ''
 PRODUCTION_DB_NAME: 'guestbook'
